id: issue_opened_intake
namespace: thanos

description: |
  Webhook entrypoint for GitHub issue events.
  Triggers the self_heal_pipeline when an issue is opened.

triggers:
  - id: github
    type: io.kestra.plugin.core.trigger.Webhook
    key: "{{ secret('WEBHOOK_KEY') }}"
    conditions:
      - type: io.kestra.plugin.core.condition.Expression
        expression: "{{ trigger.body.action == 'opened' }}"

tasks:
  - id: log_event
    type: io.kestra.plugin.core.debug.Return
    format: "Received issue event: {{ trigger.body.action }} for {{ trigger.body.repository.full_name }}"

  - id: start_pipeline
    type: io.kestra.plugin.core.flow.Subflow
    namespace: thanos
    flowId: self_heal_pipeline
    wait: false
    inputs:
      payload: "{{ trigger.body }}"