id: issue_opened_intake
namespace: thanos

description: |
  Webhook entrypoint for GitHub issues. Starts the self-heal pipeline.

inputs:
  - id: payload
    type: JSON
    required: false

tasks:
  - id: log_event
    type: io.kestra.plugin.core.log.Log
    message: |
      received webhook: body={{ (trigger is defined and trigger.body is defined) ? trigger.body : inputs.payload }}

  - id: start_pipeline
    type: io.kestra.plugin.core.flow.Subflow
    namespace: thanos
    flowId: self_heal_pipeline
    wait: false
    inputs:
      payload: "{{ (trigger is defined and trigger.body is defined) ? trigger.body : inputs.payload }}"

triggers:
  - id: github
    type: io.kestra.plugin.core.trigger.Webhook
    key: "{{ secret('WEBHOOK_KEY') }}"
    conditions:
      - type: io.kestra.plugin.core.condition.Expression
        expression: "{{ ((trigger.body.action ?? '') == 'opened') and (((trigger.body.repository.full_name ?? '') != '') or ((trigger.body.repository.clone_url ?? '') != '')) and ((trigger.body.issue.title ?? '') != '') }}"
